In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell

In [2]:
InteractiveShell.ast_node_interactivity = 'all'

# 创建数组

## array:

In [54]:
np.array([[1,2,3],[4,5,6]],dtype=float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [52]:
# frombuffer:
s = b'Hello World'
np.frombuffer(s,dtype='S1',count=-1,offset=1)

array([b'e', b'l', b'l', b'o', b' ', b'W', b'o', b'r', b'l', b'd'],
      dtype='|S1')

## arange:根据数据范围创建数组

In [55]:
np.arange(start=2,stop=17,step=2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

## linespace:创建等差数列数组

In [60]:
np.linspace(start=2,stop=17,num=6,endpoint=True)

array([ 2.,  5.,  8., 11., 14., 17.])

# 数组操作

## reshape:修改数组形状

In [105]:
arr = np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

## resize:返回指定形状的新数组

In [107]:
np.resize(arr,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

## flat:数组元素迭代器
    flat是将数组进行降维，返回迭代器

In [74]:
org = np.arange(9).reshape(3,3)
print("original array:",org,sep='\n')

print('iterate the array:')
for row in org:
    print(row)

for al in org.flat:
    print(al)

original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
iterate the array:
[0 1 2]
[3 4 5]
[6 7 8]
0
1
2
3
4
5
6
7
8


## flatten:返回一维数组的copy，对copy修改不影响原数组

In [77]:
org_fn = np.arange(8).reshape(2,4)
org_fn.flatten(order='F')

array([0, 4, 1, 5, 2, 6, 3, 7])

## ravel:功能同flatten，但返回的不是copy

In [79]:
org_rl = np.arange(8).reshape(2,4)
org_rl.flatten(order='C')

array([0, 1, 2, 3, 4, 5, 6, 7])

## 翻转数组

### transpose:对换数组的维度

In [80]:
org_te = np.arange(12).reshape(3,4)
org_te
np.transpose(org_te)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### T: 同transpose

In [81]:
org_te = np.arange(12).reshape(3,4)
org_te
org_te.T

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## rollaxis:向后滚动特定的轴到一个特定位置

In [91]:
org_rs = np.arange(8).reshape(2,2,2)
org_rs
np.rollaxis(org_rs,2,0)  #将2轴滚动到0轴（宽度到深度）

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[[0, 2],
        [4, 6]],

       [[1, 3],
        [5, 7]]])

## swapaxes:用于交换数组的两个轴

In [92]:
np.swapaxes(org_rs,2,0)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

## append:向数组添加值

In [123]:
arr_ad = np.arange(6).reshape(2,3)
arr_ad
np.append(arr_ad,[10,20,30,40])
np.append(arr_ad,[[10,20],[30,40]],axis=1)

array([[0, 1, 2],
       [3, 4, 5]])

array([ 0,  1,  2,  3,  4,  5, 10, 20, 30, 40])

array([[ 0,  1,  2, 10, 20],
       [ 3,  4,  5, 30, 40]])

## insert:在给定索引之前，沿给定轴在输入数组中插入值

In [128]:
arr_it = np.arange(6).reshape(2,3)
arr_it

np.insert(arr_it,2,[10,20])

np.insert(arr_it,2,11,axis=1)

np.insert(arr_it,2,[11,21],axis=1)

array([[0, 1, 2],
       [3, 4, 5]])

array([ 0,  1, 10, 20,  2,  3,  4,  5])

array([[ 0,  1, 11,  2],
       [ 3,  4, 11,  5]])

array([[ 0,  1, 11,  2],
       [ 3,  4, 21,  5]])

## unique:去重

In [135]:
arr_ue = np.array([[1,1,3,3],[6,6,7,7]])
arr_ue

np.unique(arr_ue)
np.unique(arr_ue,return_index=True)
np.unique(arr_ue,return_inverse=True)
np.unique(arr_ue,return_counts=True)

array([[1, 1, 3, 3],
       [6, 6, 7, 7]])

array([1, 3, 6, 7])

(array([1, 3, 6, 7]), array([0, 2, 4, 6], dtype=int64))

(array([1, 3, 6, 7]), array([0, 0, 1, 1, 2, 2, 3, 3], dtype=int64))

(array([1, 3, 6, 7]), array([2, 2, 2, 2], dtype=int64))

## np.concatenate():链接,横着连/竖着连

In [136]:
k1 = np.arange(1,7).reshape(2,3)
k2 = np.arange(5,11).reshape(2,3)
k1
k2
np.concatenate([k1,k2])

array([[1, 2, 3],
       [4, 5, 6]])

array([[ 5,  6,  7],
       [ 8,  9, 10]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# numpy 数组属性

In [6]:
ndarray = np.arange(1,7).reshape(2,3)

## ndim:秩，即轴的数量或维度的数量

In [7]:
ndarray.ndim

2

## shape:数组的维度，对于矩阵，n 行 m 列

In [8]:
ndarray.shape

(2, 3)

## size:数组元素的总个数，相当于 .shape 中 n*m 的值

In [9]:
ndarray.size

6

## dtype:对象的元素类型

In [10]:
ndarray.dtype

dtype('int32')

## itemsize:对象中每个元素的大小，以字节为单位

In [11]:
ndarray.itemsize

4

## flags:对象的内存信息

In [12]:
ndarray.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

## real:元素的实部

In [13]:
ndarray.real

array([[1, 2, 3],
       [4, 5, 6]])

## imag:元素的虚部

In [14]:
ndarray.imag

array([[0, 0, 0],
       [0, 0, 0]])

## data:包含实际数组元素的缓冲区
    由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。

In [15]:
ndarray.data

# 数学函数

## round:四舍五入

In [97]:
org_rd = np.array([1.0,5.55,  123.45353,  0.567,  25.532])
org_rd
org_rd.round(1)
np.round(org_rd,3)

array([  1.     ,   5.55   , 123.45353,   0.567  ,  25.532  ])

array([  1. ,   5.6, 123.5,   0.6,  25.5])

array([  1.   ,   5.55 , 123.454,   0.567,  25.532])

## floor:返回小于或者等于指定表达式的最大整数，即向下取整。

In [101]:
np.floor(org_rd)

array([  1.,   5., 123.,   0.,  25.])

## ceil:向上取整

In [102]:
np.ceil(org_rd)

array([  1.,   6., 124.,   1.,  26.])

# 统计函数